### ISSUE TITLE
Excuse me, when using the parser, there is a conversation too long situation how to deal with

### ISSUE THREAD

**Issue by WISH-WEI** [seq-to-mind/DDP_parsing#2]
Excuse me, when using the parser, there is a conversation too long situation how to deal with

**Comment by seq-to-mind** [comment]
You can set the inference batch size as 1.

See this line:
https://github.com/seq-to-mind/DDP_parsing/blob/a1332688d5cc2a47f9304daa4afbcabad0e22c70/main_infer.py#L30

**Comment by WISH-WEI** [comment]
Sorry to bother you again. The error problems I face are as follows, which mainly occur when using the parser：
RuntimeError: The expanded size of the tensor (584) must match the existing size (514) at non-singleton dimension 1.  Target sizes: [1, 584].  Tensor sizes: [1, 514]

**Comment by seq-to-mind** [comment]
You can paste detailed logs here, I cannot figure out where the error comes from your description.

**Comment by WISH-WEI** [comment]
/public/home/weishaohua2022/miniconda3/envs/mpddp/lib/python3.7/site-packages/requests/__init__.py:114: RequestsDependencyWarning: urllib3 (1.26.14) or chardet (None)/charset_normalizer (3.3.2) doesn't match a supported version!
  RequestsDependencyWarning,
Some weights of the model checkpoint at /public/home/weishaohua2022/DDP_parsing-main/roberta-base were not used when initializing RobertaModel: ['classifier.dense.weight', 'classifier.dense.bias', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Loading model from: ./saved_models/one_checkpoint.pth
Traceback (most recent call last):
  File "main_infer.py", line 40, in <module>
    all_sample_utter_level, all_predict_link, all_predict_relation = infer_process(model, infer_batches)
  File "main_infer.py", line 16, in infer_process
    utter_list, pred_link, pred_rel = model.batch_infer(batch)
  File "/public/home/weishaohua2022/DDP_parsing-main/Model.py", line 213, in batch_infer
    batch_sample_edu_reps = self.agent.encoding_all_utterances(batch_sample_input_text, edu_number_list=edu_number)
  File "/public/home/weishaohua2022/DDP_parsing-main/Model.py", line 32, in encoding_all_utterances
    batch_embedding_after_bert = self.language_backbone(batch_input_tensor, attention_mask=attention_mask)[0]
  File "/public/home/weishaohua2022/miniconda3/envs/mpddp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/public/home/weishaohua2022/miniconda3/envs/mpddp/lib/python3.7/site-packages/transformers/models/roberta/modeling_roberta.py", line 801, in forward
    buffered_token_type_ids_expanded = buffered_token_type_ids.expand(batch_size, seq_length)
RuntimeError: The expanded size of the tensor (584) must match the existing size (514) at non-singleton dimension 1.  Target sizes: [1, 584].  Tensor sizes: [1, 514]

**Comment by seq-to-mind** [comment]
Are you following the data format for the dialogue input?
The issue seems to be caused by a lengthy utterance; For a single utterance, it should < 512 tokens due to Roberta encoding limit.

The input data example is here, ` <utterance> ` is a delimiter.
https://github.com/seq-to-mind/DDP_parsing/blob/a1332688d5cc2a47f9304daa4afbcabad0e22c70/data/text_for_inference.txt#L1

To truncate the lengthy utterance, you can change the tokenization config:
` batch_tokenized = self.tokenizer(input_sequence_list, return_tensors="pt", padding=True, truncation=True, max_length=512)`
in this line:
https://github.com/seq-to-mind/DDP_parsing/blob/a1332688d5cc2a47f9304daa4afbcabad0e22c70/Model.py#L29

**Comment by WISH-WEI** [comment]
Thank you very much for your patience and advice！！
If I don't want to intercept and need to set a maximum length limit, what parameters do I need to change and do I need to retrain the main_train.py file?

**Comment by seq-to-mind** [comment]
(1 )You can use other language models with support larger context windows (e.g., XLNet).  
(2) Actually as the encoding step is performed on utterance level, usually one utterance will not exceed 512 tokens. Moreover, even if the utterance length is too big, the information needed for discourse parsing might be sufficient within a 512 context window, thus I suppose truncation works for most cases.

**Comment by seq-to-mind** [comment]
Hi, 

I suppose this issue https://github.com/seq-to-mind/DDP_parsing/issues/4 is same as yours, and i have updated the repo to fix it.

You can refer to my reply here https://github.com/seq-to-mind/DDP_parsing/issues/4#issuecomment-1878074477 for the solution.
